name: Publish npm package to github package
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - uses: actions/checkout@v3
      - name: Get tag version
        if: startsWith(github.ref, 'refs/tags/')
        id: get_tag_version
        run: echo TAG_VERSION=${GITHUB_REF/refs\/tags\//} >> $GITHUB_OUTPUT

      # Setup deno
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: test
        run: deno task test
        env:
          HF_READ_TOKEN: ${{ secrets.HF_READ_TOKEN }}

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
      - name: npm build
        run: deno task build ${{steps.get_tag_version.outputs.TAG_VERSION}}
      - name: npm publish
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd npm && npm publish
