name: Publish npm package to github package
on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to publish"
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - uses: actions/checkout@v3

      # Setup deno
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: test
        run: deno task test
        env:
          HF_READ_TOKEN: ${{ secrets.HF_READ_TOKEN }}

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get tag version
        id: get_tag_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "::set-output name=tag::${{ github.event.inputs.tag }}"
          elif [ "${{ github.event_name }}" = "release" ]; then
            echo "::set-output name=tag::${{ github.event.release.tag_name }}"
          fi

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"
          registry-url: "https://npm.pkg.github.com"
      - name: npm build
        run: deno task build ${{steps.get_tag_version.outputs}}
      - name: npm publish
        if: startsWith(github.ref, 'refs/tags/')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: cd npm && npm publish
