name: Test
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - uses: actions/checkout@v3
      # Setup deno
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      # test
      - name: run the test
        run: deno task test
        env:
          HF_READ_TOKEN: ${{ secrets.HF_READ_TOKEN }}
